FROM python:3.11-slim-bullseye

WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the client application files
COPY . .

# Expose port 8501 for Streamlit
EXPOSE 8501

# Set the default command
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]